### ISSUE TITLE
Freezing constant does not ensure they can't be changed

### ISSUE THREAD

**Issue by Electron-libre** [synbioz/guidelines#6]
> freeze constants to ensure they can't be changed

This false, wrong, or inaccurate.
Freezing constant does not ensure they can't be changed. It only mean that bound object will be immutable.
This is not the constant that is frozen but it's value. 
You stil can reassign constant's value.
But you can't modify bound object.

```
irb(main):001:0> CONST = 'in the universe everything change constantly, this nether change, lovely paradox ...'.freeze
=> "in the universe everything change constantly, this nether change, lovely paradox ..."
irb(main):002:0> CONST << 'do you agree ?' 
RuntimeError: can't modify frozen String
    from (irb):2
    from /home/cedric/.rbenv/versions/2.1.5/bin/irb:11:in `<main>'
irb(main):003:0> CONST = 'nothing will nether change'
(irb):3: warning: already initialized constant CONST
(irb):1: warning: previous definition of CONST was here
=> "nothing will nether change"
irb(main):004:0> CONST
=> "nothing will nether change"
```

So I suggest that you should clarify that it is the bound object that will be immutable, but constant itself still can change …

**Comment by Bounga** [comment]
Yes it's the value that can't be changed. I'll clarify that.
